### PR TITLE
[Draft] Adding support for smooth paths

### PR DESCRIPTION
**Pull request by francoisthire**
Solve #33 

## Context

This PR adds two functions `smooth_ccurve` and `smooth_qcurve` which allow to define `smooth` curves. One of the control points is defined depending on the previous curve. 

The function `smooth_ccurve` corresponds to `s` and `S` SVG path commands, while `smooth_qcurve` corresponds to `t` and `T` SVG path commands. More details [here](https://www.w3.org/TR/SVG2/paths.html#PathDataCubicBezierCommands)

TODO:

- [x] Check the PR compiles correctly (I did not find `brzo` on opam. I will pin it later)
- [x] Add some tests
- [x] Update `CHANGES.md`

## Questions to the reviewers

- Which kind of test should be added? Some few unit tests?

### CODE REVIEW

**Comment by dbuenzli** [comment]
> [ ] Check the PR compiles correctly (I did not find `brzo` on opam. I will pin it later)

The official build system is still `topkg` so simply `opam install topkg-care` and do `topkg build`.

**Comment by dbuenzli** [comment]
> * Which kind of test should be added?

You can add a sample image in [the database](https://github.com/dbuenzli/vg/blob/master/db/README.md), named
`path-smooth`, that shows use of the combinators see for example [`path-cubics`](https://erratique.ch/software/vg/demos/rhtmlc#path-cubics) ([src](https://github.com/dbuenzli/vg/blob/master/db/paths.ml#L37)).

You can then have a look at the results by running for example `rsvg.native`. See [here](https://github.com/dbuenzli/vg?tab=readme-ov-file#sample-programs-and-images) on how to build the tests. One day I hope to have a raster renderer and expect test the renders with [pixeldrift](https://erratique.ch/software/pixeldrift). But meanwhile that should do.

**Comment by francoisthire** [comment]
I followed your instructions:

- The project compiles correctly with `topkg`
- I have added a test ensuring smooth paths work correctly (I was not very inspired and used the classical quarter circle approximation). The code is a bit ugly but should be easy to understand.

**Comment by francoisthire** [comment]
I have updated the `CHANGES` file. Let me know if there is anything more that I can do.

**Comment by dbuenzli** [comment]
Thanks! 

I squashed your patches into 3b3cea5 and 2d77ab2 and cosmetically massaged them in 33e1952.

Using trigonometry to compute point reflections felt rather heavy weight (and more expensive) so in 1e690d3 I replaced computations by simple linear algrebra following this diagram:

reflect

**Comment by francoisthire** [comment]
Perfect, thanks!

**Pull request closed without merging**
